# Generated by Django 3.1.3 on 2020-12-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'category_name',
                    models.CharField(max_length=300, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('product_name', models.CharField(max_length=300)),
                ('nutriscore', models.CharField(max_length=1)),
                ('barcode', models.PositiveBigIntegerField(unique=True)),
                ('image_url', models.URLField(max_length=300)),
                ('energy_kj', models.CharField(max_length=20)),
                ('energy_kcal', models.CharField(max_length=20)),
                ('protein', models.CharField(max_length=20)),
                ('glucid', models.CharField(max_length=20)),
                ('lipid', models.CharField(max_length=20)),
                ('fiber', models.CharField(max_length=20)),
                ('salt', models.CharField(max_length=20)),
                (
                    'categories',
                    models.ManyToManyField(to='app_products.FoodCategory'),
                ),
            ],
        ),
    ]
