# Generated by Django 3.1.3 on 2020-11-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_auto_20201126_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodproduct',
            old_name='product_name_fr',
            new_name='product_name',
        ),
    ]
