# Generated by Django 3.1.3 on 2020-11-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_auto_20201126_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodproduct',
            old_name='category',
            new_name='categories',
        ),
    ]
